[project]
name = "met-museum-european-paintings-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.53.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.2",
    "qdrant-client[fastembed]>=1.18.0",
    "sentence-transformers>=5.6.1",
    "streamlit>=1.60.0",
]
